name: kskfinance  # Changed from vasool_diary to match new project
description: "KSK Finance Management App"
publish_to: 'none'

version: 1.0.5+28  # Incremented version code

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Database
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # UI Components
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.0
  dropdown_search: ^6.0.2
  searchable_paginated_dropdown: ^1.3.0
  
  # Charts (compatible version)
  fl_chart: ^0.68.0
  
  # Utilities
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  
  # File Operations
  pdf: ^3.11.1
  printing: ^5.14.2
  share_plus: ^12.0.0
  url_launcher: ^6.3.1
  cross_file: ^0.3.4+2
  
  # Network
  http: ^1.2.2
  
  # Security
  flutter_secure_storage: ^9.2.2
  
  # File System
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  open_file: ^3.5.10
  
  # Other
  mime: ^2.0.0
  http_parser: ^4.1.1
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf